Added view for a single revision in the GUI Adding support to rebase and push after testing Integrated existing git hooks in order to for dx-push to fail fast Introduced Revision Type to differentiate between testing and pushing Merge jenkins monitor and jenkins client to provide simpler (blocking) API Remove retriction of single build per commit, and stop prevent multiple builds per commit

diff --git a/src/main/resources/pre-receive b/src/main/resources/pre-receive
--- a/src/main/resources/pre-receive
+++ b/src/main/resources/pre-receive
@@ -9,18 +9,28 @@ function die
 	exit 1
 }
 
-print_revs()
-{
-while read oldrev newrev refname; do
-	echo "$newrev"
-done
-}
-
 GIT_DIR=$(cd $GIT_DIR; pwd -P)
 
+git fetch || die "could not update git remotes"
 
-newrev=$(print_revs | tail -1)
-curl -N -X POST "http://localhost:8080/resource/git/commit/$newrev" || die "web service call failed"
+#IP_ADDR=$(pinky -f | awk '{print $7}')
+query=""
+commit=""
+while read oldrev newrev refname; do
+	query="$query&branches=$refname"
+	commit="$newrev"
+
+	if [[ "$refname" == "refs/heads/dx-push" ]]; then
+		# Make sure one is up to date
+		git update-ref refs/heads/dx-push origin/master
+
+				# run pre-receive in order to fail fast
+		$GIT_DIR/../tools/git/hooks/pre-receive <<< "$oldrev $newrev $refname"
+		[[ $? -ne 0 ]] && die "Git hooks rejected push".
+	fi
+done
+
+curl -N -X POST "http://localhost:8080/resource/git/$commit?$query" || die "web service call failed"
 
 # Reject the commit to prevent users from altering the git repo.
 exit 1
