Fixing build issues with jersey Manifests Changed to dependencies to customer jenkins-client to workaround dependency conflicts with jackson Initial HTML GUI

diff --git a/src/main/resources/pre-receive b/src/main/resources/pre-receive
--- a/src/main/resources/pre-receive
+++ b/src/main/resources/pre-receive
@@ -1,5 +1,7 @@
-#!/bin/sh
-
+#!/bin/bash
+#
+# Copyright (c) 2013 by Delphix.
+# All rights reserved.
 
 function die
 {
@@ -18,7 +20,7 @@ GIT_DIR=$(cd $GIT_DIR; pwd -P)
 
 
 newrev=$(print_revs | tail -1)
-curl -N -X POST "http://localhost:8080/git/commit/$newrev" || die "web service call failed"
+curl -N -X POST "http://localhost:8080/resource/git/commit/$newrev" || die "web service call failed"
 
 # Reject the commit to prevent users from altering the git repo.
 exit 1
